on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    concurrency:
      group: release-prs-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          manifest-file: "release-please.manifest.json"
          config-file: "release-please-config.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: "main"
